<script setup>
import { nextTick, onMounted, ref } from 'vue'
import { streamAssistant } from '../api/assistant'
import PageContainer from '../components/common/PageContainer.vue'

const prompts=['这个周末有什么值得去的活动？','有哪些适合亲子的活动？','最近有什么展览？','夏日爵士音乐会有什么票？']
const messages=ref([]);const input=ref('');const loading=ref(false);const chat=ref(null);const composer=ref(null);let controller=null
function makeId(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`} function memory(){let id=localStorage.getItem('cityhub_ai_memory_id');if(!id){id=makeId();localStorage.setItem('cityhub_ai_memory_id',id)}return id}function scroll(){nextTick(()=>{if(chat.value)chat.value.scrollTop=chat.value.scrollHeight})}function resize(){nextTick(()=>{const e=composer.value;if(e){e.style.height='auto';e.style.height=`${Math.min(e.scrollHeight,160)}px`}})}function newConversation(){controller?.abort();localStorage.setItem('cityhub_ai_memory_id',makeId());messages.value=[];input.value='';resize()}
function renderAssistant(content){return content.replace(/[&<>"']/g,(char)=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[char]).replace(/(\/activities\/\d+)/g,'<a href="$1">$1</a>')}
async function send(text=input.value){const content=text.trim();if(!content||loading.value)return;messages.value.push({role:'user',content});messages.value.push({role:'assistant',content:'',streaming:true});input.value='';resize();loading.value=true;controller=new AbortController();scroll();try{await streamAssistant(content,memory(),controller.signal,(chunk)=>{messages.value.at(-1).content+=chunk;scroll()})}catch(error){if(error.name!=='AbortError')messages.value.at(-1).content='AI 顾问暂时无法响应，请稍后重试。'}finally{const last=messages.value.at(-1);if(last)last.streaming=false;loading.value=false;controller=null;scroll()}}
function stop(){controller?.abort()} onMounted(()=>{memory();composer.value?.focus()})
</script>
<template><PageContainer><main class="assistant"><header class="assistant-head"><div><p class="eyebrow">CityHub guide</p><h1>CityHub AI 顾问</h1><p>找活动、问票券、规划你的城市周末。</p></div><el-button plain @click="newConversation">新对话</el-button></header><section ref="chat" class="chat"><div v-if="!messages.length" class="welcome"><h2>今天想去哪里走走？</h2><div class="suggestions"><button v-for="prompt in prompts" :key="prompt" @click="send(prompt)">{{ prompt }}</button></div></div><article v-for="(item,index) in messages" :key="index" :class="['message',item.role]"><span>{{ item.role==='user'?'你':'AI' }}</span><p v-if="item.role==='assistant'" v-html="renderAssistant(item.content)" /><p v-else>{{ item.content }}</p><i v-if="item.streaming" /></article></section><footer class="composer"><textarea ref="composer" v-model="input" rows="1" placeholder="问问活动、地点或预约凭证..." @input="resize" @keydown.enter.exact.prevent="send()"/><el-button v-if="loading" type="warning" @click="stop">停止生成</el-button><el-button v-else type="primary" :disabled="!input.trim()" @click="send()">发送</el-button></footer></main></PageContainer></template>
<style scoped>.assistant{max-width:900px;margin:0 auto}.assistant-head{display:flex;justify-content:space-between;align-items:flex-start;gap:var(--space-4);padding-bottom:var(--space-5);border-bottom:1px solid var(--color-border)}h1{margin:var(--space-2) 0;font-family:Georgia,"Songti SC",serif;font-size:clamp(2rem,4vw,3.4rem);letter-spacing:-.06em}.assistant-head p:not(.eyebrow){margin:0;color:var(--color-text-secondary)}.chat{min-height:480px;max-height:60vh;overflow:auto;padding:var(--space-6) 0}.welcome{text-align:center;padding:var(--space-7) 0}.welcome h2{font-family:Georgia,"Songti SC",serif}.suggestions{display:flex;flex-wrap:wrap;justify-content:center;gap:var(--space-2);margin-top:var(--space-5)}.suggestions button{padding:10px 14px;border:1px solid var(--color-border);border-radius:999px;background:var(--color-surface);color:var(--color-primary);cursor:pointer}.message{display:flex;gap:var(--space-3);margin-bottom:var(--space-4)}.message>span{display:grid;place-items:center;width:32px;height:32px;border-radius:50%;background:var(--color-primary-soft);color:var(--color-primary);font-size:.78rem;font-weight:700}.message p{max-width:min(680px,82%);margin:0;padding:12px 15px;border-radius:var(--radius-md);background:var(--color-surface);box-shadow:var(--shadow-sm);white-space:pre-wrap;line-height:1.7}.message :deep(a){color:var(--color-accent);font-weight:700;text-decoration:underline}.message.user{flex-direction:row-reverse}.message.user>span{background:var(--color-accent-soft);color:var(--color-accent)}.message.user p{background:var(--color-primary);color:#fff}.message i{display:inline-block;width:6px;height:1em;margin-left:3px;background:var(--color-primary);vertical-align:middle;animation:blink 1s step-end infinite}@keyframes blink{50%{opacity:0}}.composer{display:flex;align-items:flex-end;gap:var(--space-2);padding:var(--space-4);border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-surface)}textarea{flex:1;min-height:42px;max-height:160px;border:0;outline:0;resize:none;font:inherit;line-height:1.5;background:transparent}@media(max-width:767px){.chat{min-height:420px;padding:var(--space-5) 0}.assistant-head{align-items:center}.suggestions{justify-content:flex-start}.message p{max-width:78%}.composer{padding:var(--space-3)}}</style>
