<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { getFollowFeed, getHotBlogs, publishBlog } from '../api/blog'
import { getActivitiesPage } from '../api/activity'
import { useUserStore } from '../stores/user'
import PageContainer from '../components/common/PageContainer.vue'; import PageLoading from '../components/common/PageLoading.vue'; import EmptyState from '../components/common/EmptyState.vue'; import ErrorState from '../components/common/ErrorState.vue'; import SectionHeader from '../components/common/SectionHeader.vue'; import BlogCard from '../components/business/BlogCard.vue'
const route=useRoute(); const router=useRouter(); const userStore=useUserStore(); const blogs=ref([]); const activities=ref({}); const loading=ref(false); const error=ref(false); const current=ref(1); const hasMore=ref(true); const minTime=ref(Date.now()); const offset=ref(0); const publishOpen=ref(false); const publishing=ref(false); const form=ref({activityId:null,title:'',content:''})
const tab=computed(()=>route.query.tab==='following'?'following':'hot'); const activityList=computed(()=>Object.values(activities.value))
async function loadActivities(){const [a,b]=await Promise.all([getActivitiesPage({current:1,size:10}),getActivitiesPage({current:2,size:10})]); activities.value=Object.fromEntries([...(a.data||[]),...(b.data||[])].map(item=>[item.id,item]))}
async function load(reset=true){if(tab.value==='following'&&!userStore.isLoggedIn){blogs.value=[];loading.value=false;return}loading.value=true;error.value=false;try{if(tab.value==='hot'){if(reset)current.value=1;const list=await getHotBlogs(current.value)||[];blogs.value=reset?list:[...blogs.value,...list];hasMore.value=list.length===10}else{if(reset){blogs.value=[];minTime.value=Date.now();offset.value=0;hasMore.value=true}const result=await getFollowFeed({lastId:minTime.value,offset:offset.value});const list=result?.list||[];blogs.value=reset?list:[...blogs.value,...list];minTime.value=result?.minTime||minTime.value;offset.value=result?.offset||0;hasMore.value=list.length===2}}catch{error.value=true}finally{loading.value=false}}
function switchTab(next){router.push({path:'/community',query:{tab:next}})} function login(){router.push({name:'login',query:{redirect:route.fullPath}})} function loadMore(){if(tab.value==='hot'){current.value+=1;load(false)}else load(false)}
async function submit(){if(!form.value.activityId||!form.value.title.trim()||!form.value.content.trim()) return ElMessage.warning('请选择活动，并填写标题和正文');publishing.value=true;try{await publishBlog({activityId:form.value.activityId,title:form.value.title.trim(),content:form.value.content.trim(),images:''});publishOpen.value=false;form.value={activityId:null,title:'',content:''};ElMessage.success('发布成功');switchTab('hot');await load(true)}finally{publishing.value=false}}
watch(tab,()=>load(true));onMounted(async()=>{try{await loadActivities()}catch{error.value=true} await load(true)})
</script>
<template>
  <PageContainer>
    <main class="community">
      <div class="community-head"><SectionHeader eyebrow="City voices" title="城市动态" description="看看大家最近去了哪里。" /><el-button type="primary" @click="userStore.isLoggedIn ? publishOpen = true : login">发布体验</el-button></div>
      <div class="tabs"><button :class="{ active: tab === 'hot' }" @click="switchTab('hot')">热门动态</button><button :class="{ active: tab === 'following' }" @click="switchTab('following')">关注</button></div>
      <section v-if="tab === 'following' && !userStore.isLoggedIn" class="login-prompt"><h2>登录后查看你关注的人最近分享的活动体验。</h2><el-button type="primary" @click="login">登录</el-button></section>
      <PageLoading v-else-if="loading && !blogs.length" />
      <ErrorState v-else-if="error" message="动态加载失败，请稍后重试。" @retry="() => load(true)" />
      <EmptyState v-else-if="!blogs.length" :title="tab === 'hot' ? '暂时还没有活动动态' : '关注一些有趣的人，他们的新动态会出现在这里。'" :description="tab === 'hot' ? '成为第一个分享活动体验的人。' : '去热门动态发现值得关注的城市同好。'"><el-button v-if="tab === 'following'" plain @click="switchTab('hot')">查看热门动态</el-button></EmptyState>
      <div v-else class="feed"><BlogCard v-for="blog in blogs" :key="blog.id" :blog="blog" :activities="activities" /><el-button v-if="hasMore" plain :loading="loading" @click="loadMore">加载更多</el-button><p v-else class="feed-end">已经到底了</p></div>
    </main>
    <el-dialog v-model="publishOpen" width="min(92vw, 560px)" title="发布活动体验"><el-form label-position="top"><el-form-item label="关联活动" required><el-select v-model="form.activityId" placeholder="选择你参加过的活动" filterable><el-option v-for="item in activityList" :key="item.id" :label="item.title" :value="item.id" /></el-select></el-form-item><el-form-item label="标题" required><el-input v-model="form.title" maxlength="80" show-word-limit placeholder="写下这次体验的标题" /></el-form-item><el-form-item label="正文" required><el-input v-model="form.content" type="textarea" :rows="5" maxlength="800" show-word-limit placeholder="分享现场、感受或实用建议" /></el-form-item></el-form><template #footer><el-button @click="publishOpen = false">取消</el-button><el-button type="primary" :loading="publishing" @click="submit">发布</el-button></template></el-dialog>
  </PageContainer>
</template>
<style scoped>.community{max-width:820px;margin:0 auto}.community-head{display:flex;align-items:center;justify-content:space-between;gap:var(--space-4)}.tabs{display:flex;gap:var(--space-2);margin:var(--space-5) 0}.tabs button{padding:9px 16px;border:1px solid var(--color-border);border-radius:999px;background:var(--color-surface);color:var(--color-text-secondary);cursor:pointer}.tabs button.active{border-color:var(--color-primary);background:var(--color-primary);color:#fff}.feed{display:grid;gap:var(--space-4)}.feed>.el-button{justify-self:center;margin-top:var(--space-2)}.feed-end{text-align:center;color:var(--color-text-muted);font-size:.85rem}.login-prompt{padding:var(--space-7);border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-surface-muted);text-align:center}.login-prompt h2{max-width:390px;margin:0 auto var(--space-5);font-size:1.1rem;line-height:1.6}@media(max-width:767px){.community-head{align-items:flex-end}.community-head :deep(.section-header){margin-bottom:0}.community-head .el-button{flex:0 0 auto}.tabs{margin-top:var(--space-4)}}</style>
