<script setup>
import { onMounted, ref } from 'vue'
import { getMyBlogs } from '../api/blog'
import { getActivitiesPage } from '../api/activity'
import { useUserStore } from '../stores/user'
import PageContainer from '../components/common/PageContainer.vue'; import PageLoading from '../components/common/PageLoading.vue'; import EmptyState from '../components/common/EmptyState.vue'; import ErrorState from '../components/common/ErrorState.vue'; import SectionHeader from '../components/common/SectionHeader.vue'; import BlogCard from '../components/business/BlogCard.vue'
const userStore=useUserStore(); const blogs=ref([]); const activities=ref({}); const loading=ref(true); const error=ref(false)
function mask(phone){return phone?.length===11?`${phone.slice(0,3)}****${phone.slice(-4)}`:''} async function load(){loading.value=true;error.value=false;try{const [data,a,b]=await Promise.all([getMyBlogs(),getActivitiesPage({current:1,size:10}),getActivitiesPage({current:2,size:10})]);blogs.value=data||[];activities.value=Object.fromEntries([...(a.data||[]),...(b.data||[])].map(item=>[item.id,item]))}catch{error.value=true}finally{loading.value=false}}onMounted(load)
</script>
<template><PageContainer><main class="profile"><section class="profile-head"><el-avatar :size="76" :src="userStore.user?.icon">{{ userStore.user?.nickName?.slice(0,1)||'城' }}</el-avatar><div><p class="eyebrow">My CityHub</p><h1>{{ userStore.user?.nickName || 'CityHub 用户' }}</h1><p v-if="userStore.user?.phone">{{ mask(userStore.user.phone) }}</p><p v-else>记录城市里值得再想起的片刻。</p></div></section><SectionHeader eyebrow="My notes" title="我的动态" description="你分享过的活动体验都在这里。"/><PageLoading v-if="loading"/><ErrorState v-else-if="error" message="我的动态加载失败，请稍后重试。" @retry="load"/><EmptyState v-else-if="!blogs.length" title="还没有发布过活动体验" description="去发现活动，记录你的城市生活。"><RouterLink to="/activities"><el-button type="primary">发现活动</el-button></RouterLink></EmptyState><div v-else class="my-blogs"><BlogCard v-for="blog in blogs" :key="blog.id" :blog="blog" :activities="activities"/></div></main></PageContainer></template>
<style scoped>.profile{max-width:820px;margin:0 auto}.profile-head{display:flex;align-items:center;gap:var(--space-4);margin-bottom:var(--space-8);padding:var(--space-6);border:1px solid var(--color-border);border-radius:var(--radius-xl);background:var(--color-surface-muted)}.profile-head h1{margin:var(--space-2) 0;font-family:Georgia,"Songti SC",serif;font-size:2rem;letter-spacing:-.05em}.profile-head p:not(.eyebrow){margin:0;color:var(--color-text-secondary)}.my-blogs{display:grid;gap:var(--space-4)}@media(max-width:767px){.profile-head{margin-bottom:var(--space-6);padding:var(--space-5)}.profile-head h1{font-size:1.65rem}}</style>
